### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by douglascrp** [jpotts/share-site-space-templates#1]
Hey @jpotts 

I'm trying your addon, and it works really well.
Thank you for sharing it.

But I'd like to suggest something, which is to use, by default, another folder instead of the ootb Space Templates.
Why? Because for users that actually use the Space Templates folders for other use cases, like project's templates, it is weird to see a template named site-dashboard. It makes no sense.

I thought about creating a new folder, maybe Site Templates or something like that, and use that one.

Let me know what you think.

**Comment by jpotts** [comment]
I like this suggestion. Maybe "Site Space Templates" or "Site Folder Templates" is most explicit.

Regardless of what it is called, perhaps we could update the add-on to check the new location first, then check Space Templates second, then error. That would keep it backwards compatible.

**Comment by douglascrp** [comment]
I'm ok with that.
How about using the addon to bootstrap the new folder?

**Comment by jpotts** [comment]
Yes, makes total sense.

**Comment by jpotts** [comment]
Thanks for the PR, Douglas!
